### PR TITLE
poop: build with zig 0.14.1

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
```
   ==> zig build --prefix /opt/homebrew/Cellar/poop/0.5.0_1 -Doptimize=ReleaseSafe -Dcpu=apple_m1
  install
  +- install poop
     +- zig build-exe poop ReleaseSafe native-native 1 errors
  src/main.zig:201:55: error: expected type '*void', found '*os.linux.perf_event_attr'
                  perf_fd.* = std.posix.perf_event_open(&attr, 0, -1, perf_fds[0], PERF.FLAG.FD_CLOEXEC) catch |err| {
                                                        ^~~~~
  src/main.zig:201:55: note: pointer type child 'os.linux.perf_event_attr' cannot cast into pointer type child 'void'
  /opt/homebrew/Cellar/zig/0.14.1/lib/zig/std/os/linux.zig:8508:36: note: struct declared here
  pub const perf_event_attr = extern struct {
                              ~~~~~~~^~~~~~
  /opt/homebrew/Cellar/zig/0.14.1/lib/zig/std/posix.zig:7286:11: note: parameter type declared here
      attr: *system.perf_event_attr,
            ^~~~~~~~~~~~~~~~~~~~~~~
  referenced by:
      main: /opt/homebrew/Cellar/zig/0.14.1/lib/zig/std/start.zig:660:37
      comptime: /opt/homebrew/Cellar/zig/0.14.1/lib/zig/std/start.zig:58:30
      2 reference(s) hidden; use '-freference-trace=4' to see all references
  error: the following command failed with 1 compilation errors:
  /opt/homebrew/Cellar/zig/0.14.1/bin/zig build-exe -OReleaseSafe -target native-native -mcpu apple_m1 -Mroot=/private/tmp/poop-20250609-9043-vp301s/poop-0.5.0/src/main.zig --cache-dir /private/tmp/poop-20250609-9043-vp301s/poop-0.5.0/.zig-cache --global-cache-dir /private/tmp/poop-20250609-9043-vp301s/poop-0.5.0/.brew_home/.cache/zig --name poop --zig-lib-dir /opt/homebrew/Cellar/zig/0.14.1/lib/zig/ --listen=- 
  Build Summary: 0/3 steps succeeded; 1 failed
  install transitive failure
  +- install poop transitive failure
     +- zig build-exe poop ReleaseSafe native-native 1 errors
  error: the following build command failed with exit code 1:
  /private/tmp/poop-20250609-9043-vp301s/poop-0.5.0/.zig-cache/o/24c3c418be12a9bf8662d5e8b33993c9/build /opt/homebrew/Cellar/zig/0.14.1/bin/zig /opt/homebrew/Cellar/zig/0.14.1/lib/zig /private/tmp/poop-20250609-9043-vp301s/poop-0.5.0 /private/tmp/poop-20250609-9043-vp301s/poop-0.5.0/.zig-cache /private/tmp/poop-20250609-9043-vp301s/poop-0.5.0/.brew_home/.cache/zig --seed 0x521cc415 -Z5f85b584ed794823 --prefix /opt/homebrew/Cellar/poop/0.5.0_1 -Doptimize=ReleaseSafe -Dcpu=apple_m1
```
